# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category1',
        ),
        migrations.AlterModelOptions(
            name='category1',
            options={'verbose_name': 'Категория1', 'verbose_name_plural': 'Категории1'},
        ),
    ]
