# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180925_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryhierarchy',
            name='cat1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Category1', verbose_name='Категория1'),
        ),
        migrations.AlterField(
            model_name='categoryhierarchy',
            name='cat2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Category2', verbose_name='Категория2'),
        ),
        migrations.AlterField(
            model_name='categoryhierarchy',
            name='cat3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Category3', verbose_name='Категория3'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='cat_hierar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.CategoryHierarchy', verbose_name='Иерархия категорий'),
        ),
    ]
