# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180925_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото1'),
        ),
    ]
