# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180926_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото2'),
        ),
        migrations.AddField(
            model_name='thing',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото3'),
        ),
        migrations.AddField(
            model_name='thing',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото4'),
        ),
        migrations.AddField(
            model_name='thing',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото5'),
        ),
        migrations.AddField(
            model_name='thing',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото6'),
        ),
        migrations.AddField(
            model_name='thing',
            name='photo7',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото7'),
        ),
        migrations.AddField(
            model_name='thing',
            name='photo8',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото8'),
        ),
    ]
